dofile("GetVarObject")
    
local id = getvarobject("nfr2", "units", "UNITS_UNIT_EVENT", true)
local indexval = getvarobjectvalue("ABILITIES_UNIT_INDEXER")

createobject("nfr2", id)
makechange(current, "unam", "Unit Event")
makechange(current, "unsf", "(Unit Event)")
makechange(current, "upat", "")
makechange(current, "ucol", "0")
makechange(current, "umvt", "fly")
makechange(current, "uico", "")
makechange(current, "uine", "0")
makechange(current, "udro", "0")
makechange(current, "usnd", "")
makechange(current, "ushb", "")
makechange(current, "umdl", "")
makechange(current, "uubs", "")
makechange(current, "ides", "")
makechange(current, "utip", "")
makechange(current, "usca", ".01")
makechange(current, "ussc", ".01")
makechange(current, "ubdg", "0")
makechange(current, "uhom", "1")
makechange(current, "uabi", "Aloc,Avul," .. indexval)

updateobjects()